// alert action
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// register action
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// user load and authentication(login) action
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_USER_FAILED = 'GET_USER_FAILED';

// getting profile actions
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// adding teacher details and editing in user actions
export const ADD_TEACHER_DETAILS_SUCCESS = 'ADD_TEACHER_DETAILS_SUCCESS';
export const ADD_TEACHER_DETAILS_FAILED = 'ADD_TEACHER_DETAILS_FAILED';
export const DELETE_TEACHER_DETAILS_SUCCESS = 'DELETE_TEACHER_DETAILS_SUCCESS';
export const DELETE_TEACHER_DETAILS_FAILED = 'DELETE_TEACHER_DETAILS_FAILED';
export const EDIT_TEACHER_DETAILS_SUCCESS = 'EDIT_TEACHER_DETAILS_SUCCESS';
export const EDIT_TEACHER_DETAILS_FAILED = 'EDIT_TEACHER_DETAILS_FAILED';

// adding subject and editing actions
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS';
export const ADD_SUBJECT_FAILED = 'ADD_SUBJECT_FAILED';
export const EDIT_SUBJECT_SUCCESS = 'EDIT_SUBJECT_SUCCESS';
export const EDIT_SUBJECT_FAILED = 'EDIT_SUBJECT_FAILED';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAILED = 'DELETE_SUBJECT_FAILED';
